# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhihuDaily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZhihuDaily

  pod 'Alamofire', '~> 4.4'
  pod 'Kingfisher', '~> 3.0'
  pod 'SwiftyJSON'

  pod 'MMDrawerController', '~> 0.5.7'
  pod 'YYModel'

end
